// Auto-generated by Supabase MCP `generate_typescript_types` on 2026-04-23
// after migration 002_survey_idempotency_and_resume.
// Re-generate via the MCP tool whenever the schema changes; never edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      consent_log: {
        Row: {
          consent_type: string
          granted: boolean
          granted_at: string
          id: number
          ip_hash: string | null
          session_id: string | null
        }
        Insert: {
          consent_type: string
          granted: boolean
          granted_at?: string
          id?: number
          ip_hash?: string | null
          session_id?: string | null
        }
        Update: {
          consent_type?: string
          granted?: boolean
          granted_at?: string
          id?: number
          ip_hash?: string | null
          session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "consent_log_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      error_log: {
        Row: {
          created_at: string
          error_type: string | null
          id: number
          message: string | null
          session_id: string | null
          stack: string | null
        }
        Insert: {
          created_at?: string
          error_type?: string | null
          id?: number
          message?: string | null
          session_id?: string | null
          stack?: string | null
        }
        Update: {
          created_at?: string
          error_type?: string | null
          id?: number
          message?: string | null
          session_id?: string | null
          stack?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "error_log_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      schools: {
        Row: {
          canton: string | null
          created_at: string
          id: string
          name: string
          plan: string
        }
        Insert: {
          canton?: string | null
          created_at?: string
          id?: string
          name: string
          plan?: string
        }
        Update: {
          canton?: string | null
          created_at?: string
          id?: string
          name?: string
          plan?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          anonymous_id: string
          completed_at: string | null
          id: string
          school_id: string | null
          started_at: string
          user_agent_hash: string | null
        }
        Insert: {
          anonymous_id: string
          completed_at?: string | null
          id?: string
          school_id?: string | null
          started_at?: string
          user_agent_hash?: string | null
        }
        Update: {
          anonymous_id?: string
          completed_at?: string | null
          id?: string
          school_id?: string | null
          started_at?: string
          user_agent_hash?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sessions_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      survey_responses: {
        Row: {
          answer: Json
          id: number
          question_id: string
          responded_at: string
          session_id: string
          value_numeric: number | null
        }
        Insert: {
          answer: Json
          id?: number
          question_id: string
          responded_at?: string
          session_id: string
          value_numeric?: number | null
        }
        Update: {
          answer?: Json
          id?: number
          question_id?: string
          responded_at?: string
          session_id?: string
          value_numeric?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "survey_responses_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      teachers: {
        Row: {
          created_at: string
          email: string
          id: string
          school_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id: string
          school_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          school_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teachers_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      video_events: {
        Row: {
          created_at: string
          event_type: string
          id: number
          metadata: Json | null
          session_id: string
          timestamp_ms: number
          video_position_s: number | null
        }
        Insert: {
          created_at?: string
          event_type: string
          id?: number
          metadata?: Json | null
          session_id: string
          timestamp_ms: number
          video_position_s?: number | null
        }
        Update: {
          created_at?: string
          event_type?: string
          id?: number
          metadata?: Json | null
          session_id?: string
          timestamp_ms?: number
          video_position_s?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "video_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_teacher_school_id: { Args: Record<string, never>; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
